#!/usr/bin/env perl
use strict;
use warnings;

use lib map { "$ENV{HOME}/sandbox/$_/lib" } qw(MIDI-Chord-Guitar);
use MIDI::Chord::Guitar;
use Music::FretboardDiagram;

my $mcg = MIDI::Chord::Guitar->new(voicing_file => '/home/gene/sandbox/MIDI-Chord-Guitar/share/midi-guitar-chord-voicings.csv');

my @specs;

my $fingerings = $mcg->fingering('E2', 'm');
for my $fingering (@$fingerings) {
    my ($chord, $posn) = split /-/, $fingering;
    push @specs, [$posn, $chord];
}
$fingerings = $mcg->fingering('E3', 'm');
for my $fingering (@$fingerings) {
    my ($chord, $posn) = split /-/, $fingering;
    push @specs, [$posn, $chord]
        if $posn < 12;
}

@specs = sort { $a->[0] <=> $b->[0] } @specs;
use Data::Dumper::Compact qw(ddc);
warn __PACKAGE__,' L',__LINE__,' ',ddc(\@specs, {max_width=>128});

my $dia = Music::FretboardDiagram->new(
  chord    => \@specs,
  frets    => 13,
  outfile  => 'fretboard',
  horiz    => 1,
  showname => 0,
  verbose  => 1,
);

$dia->draw();
